08_pjt/community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path(
        '<int:review_pk>/comments/create/',
        views.create_comment,
        name='create_comment',
    ),
    path('<int:review_pk>/like/', views.like, name='like'),
    path('<int:review_pk>/comments/<int:comment_pk>/like/', 
         views.like_comment, 
         name='like_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/create/', 
         views.create_reply, 
         name='create_reply'),
    path('<int:review_pk>/comments/<int:comment_pk>/reply/<int:reply_pk>/like/', 
         views.like_reply, 
         name='like_reply'),
]

08_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_pk>/change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),

]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

08_pjt/community/models.py
from django.db import models
from django.conf import settings


class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_reviews'
    )


class Comment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_comments'
    )

class Reply(models.Model):
    content = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_replys'
    )

08_pjt/community/forms.py
from django import forms
from .models import Review, Comment, Reply


class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user','like_users']

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['content',]

08_pjt/community/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.views.decorators.http import (
    require_safe,
    require_POST,
    require_http_methods,
)
from .models import Review, Comment, Reply
from .forms import ReviewForm, CommentForm, ReplyForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required


@require_safe
def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews,
    }
    return render(request, 'community/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            form.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'community/create.html', context)


@require_safe
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    reply_form = ReplyForm()
    comments = review.comment_set.all()
    comment_form = CommentForm()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments,
        'reply_form': reply_form,

    }
    return render(request, 'community/detail.html', context)

@login_required
@require_POST
def create_comment(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment_form.save()
        return redirect('community:detail', review.pk)
    context = {
        'comment_form': comment_form,
        'review': review,
        'comments': review.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)

@login_required
@require_POST
def like(request, review_pk):
    review = get_object_or_404(Review,pk=review_pk)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        is_liked = False
    else:
        review.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked':is_liked,
        'likes_count':review.like_users.count()
    }
    return JsonResponse(context)

@login_required
@require_POST
def like_comment(request,review_pk,comment_pk):

    comment = get_object_or_404(Comment,pk=comment_pk)

    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
        is_liked = False
    else:
        comment.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked':is_liked,
        'likes_count':comment.like_users.count()
    }
    return JsonResponse(context)


@login_required
@require_POST
def create_reply(request, review_pk, comment_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment = get_object_or_404(Comment, pk=comment_pk)
    reply_form = ReplyForm(request.POST)
    if reply_form.is_valid():
        reply = reply_form.save(commit=False)
        reply.comment = comment
        reply.user = request.user
        reply_form.save()
        return redirect('community:detail', review.pk)
    context = {
        'reply_form': reply_form,
        'review': review,
        'replys': comment.reply_set.all(),
    }
    return render(request, 'community/detail.html', context)


@login_required
@require_POST
def like_reply(request,review_pk,comment_pk, reply_pk):
    reply = get_object_or_404(Reply, pk=reply_pk)

    if request.user in reply.like_users.all():
        reply.like_users.remove(request.user)
        is_liked = False
    else:
        reply.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked':is_liked,
        'reply_likes_count':reply.like_users.count()
    }
    return JsonResponse(context)

08_pjt/community/templates/community/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'community:index' %}">[back]</a>
{% endblock %}

08_pjt/community/templates/community/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="text-center">DETAIL</h2>
  <h3>{{ review.pk }} 번째 글</h3>
  <hr>
  <p>제목: {{ review.title }}</p>
  <p>영화 제목: {{ review.movie_title }}</p>
  <p>내용: {{ review.content }}</p>
  <p>평점: {{ review.rank }}</p>
  <p>작성 시각: {{ review.created_at }}</p>
  <p>수정 시각: {{ review.updated_at }}</p>
  <hr>
  <h4>댓글 목록</h4>
  {% if comments|length %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  {% for comment in comments %}
    <div>
      {{ comment.user }} - {{ comment.content }} 
      <form class="like-forms" data-comment-id="{{ comment.pk }}" data-review-id="{{ review.pk}}">
        {% csrf_token %}
        {% if request.user in comment.like_users.all %}
        <button class="fa-solid fa-heart" id="like-{{comment.pk}}">

        </button>
        {% else %}
        <button class="fa-regular fa-heart" id="like-{{comment.pk}}">
    
        </button>
        {% endif %}
      </form>
      좋아요 갯수:<span id="likes-count-{{ comment.pk }}">{{ comment.like_users.all|length }}</span>
      <ul>
        {% for reply in comment.reply_set.all %}
        <li>{{ reply.user }} - {{ reply.content }}

            <form class="reply-like-forms" data-reply-id="{{ reply.pk }}" data-comment-id="{{ comment.pk}}" data-review-id="{{ review.pk}}">
                {% csrf_token %}
                {% if request.user in reply.like_users.all %}
                <button id="reply-like-{{reply.pk}}">좋아요 취소</button>
                {% else %}
                <button id="reply-like-{{reply.pk}}">좋아요</button>
                {% endif %}
              </form>
              대댓글 좋아요 갯수:<span id="reply-likes-count-{{ reply.pk }}">{{ reply.like_users.all|length }}</span>
        </li>

        {% endfor %}
      </ul>
      

      {% if user.is_authenticated %}
    <form action="{% url 'community:create_reply' review.pk comment.pk %}" method="POST">
      {% csrf_token %}
      {{reply_form.as_p}}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[대댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
    </div>
  {% empty %}
    <p><b>댓글이 없어요..</b></p>
  {% endfor %}
  <hr>
  {% if user.is_authenticated %}
    <form action="{% url 'community:create_comment' review.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <a href="{% url 'community:index' %}">[back]</a>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const formTags = document.querySelectorAll('.like-forms')
    const replyFormTags = document.querySelectorAll('.reply-like-forms')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    formTags.forEach((formTag)=>{
        formTag.addEventListener('submit',function(event){
            event.preventDefault()
            const commentId = formTag.dataset.commentId
            const reviewId = formTag.dataset.reviewId
            axios({
                url:`/community/${reviewId}/comments/${commentId}/like/`,
                method : "post",
                headers: {'X-CSRFToken': csrftoken}
            })
                .then((response)=>{
                    const isLiked=response.data.is_liked
                    const likeBtn = document.querySelector(`#like-${commentId}`)
                    if (isLiked===true) {
                        likeBtn.setAttribute("class", "fa-solid fa-heart")
                    } else {
                        likeBtn.setAttribute("class", "fa-regular fa-heart")
                    }
                    const likesCountTag = document.querySelector(`#likes-count-${commentId}`)
                    likesCountTag.textContent = response.data.likes_count
                })
                .catch((error)=>{
                    console.log(error)
                })
        })
    })

    replyFormTags.forEach((replyFormTag)=>{
        replyFormTag.addEventListener('submit',function(event){
            event.preventDefault()
            const commentId = replyFormTag.dataset.commentId
            const replyId = replyFormTag.dataset.replyId
            const reviewId = replyFormTag.dataset.reviewId
            axios({
                url:`/community/${reviewId}/comments/${commentId}/reply/${replyId}/like/`,
                method : "post",
                headers: {'X-CSRFToken': csrftoken}
            })
                .then((response)=>{
                    const isLiked=response.data.is_liked
                    const likeBtn = document.querySelector(`#reply-like-${replyId} > i`)
                    if (isLiked===true) {
                        likeBtn.setAttribute("class", "fa-solid fa-heart")
                    } else {
                        likeBtn.setAttribute("class", "fa-regular fa-heart")
                    }
                    const replyLikesCountTag = document.querySelector(`#reply-likes-count-${replyId}`)
                    replyLikesCountTag.textContent = response.data.reply_likes_count
                })
                .catch((error)=>{
                    console.log(error)
                })
        })
    })
  </script>

{% endblock  %}

08_pjt/community/templates/community/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Community</h1>
  <hr>
  {% for review in reviews %}
    <p>작성자 : <a href="{% url 'accounts:profile' review.user.username %}">{{ review.user }}</a></p>
    <p>글 번호: {{ review.pk }}</p>
    <p>글 제목: {{ review.title }}</p>
    <p>글 내용: {{ review.content }}</p>
    <form class="like-forms" data-review-id="{{ review.pk }}">
      {% csrf_token %}
      {% if request.user in review.like_users.all %}
      <button id="like-{{ review.pk}}">좋아요 취소</button>
      {% else %}
      <button id="like-{{ review.pk}}">좋아요</button>
      {% endif %}
    </form>
    <p>
      <span id="likes-count-{{review.pk}}">{{ review.like_users.all|length }}</span> 명이 이 글을 좋아합니다.
    </p>
    <a href="{% url 'community:detail' review.pk %}">[detail]</a>
    <hr>
  {% endfor %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const formTags = document.querySelectorAll('.like-forms')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    formTags.forEach((formTag)=>{
        formTag.addEventListener('submit',function(event){
            event.preventDefault()
            const reviewId = formTag.dataset.reviewId
            axios({
                url:`/community/${reviewId}/like/`,
                method : "post",
                headers: {'X-CSRFToken': csrftoken}
            })
                .then((response)=>{
                    const isLiked=response.data.is_liked
                    const likeBtn = document.querySelector(`#like-${reviewId}`)
                    if (isLiked===true) {
                        likeBtn.innerText = "좋아요 취소"
                    } else {
                        likeBtn.innerText = "좋아요"
                    }
                    const likesCountTag = document.querySelector(`#likes-count-${reviewId}`)
                    likesCountTag.textContent = response.data.likes_count
                })
                .catch((error)=>{
                    console.log(error)
                })
        })
    })
  </script>
{% endblock %}