08_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
]

08_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/',views.create,name='create'),
    path('<int:movie_pk>/',views.detail,name='detail'),
    path('<int:movie_pk>/update/',views.update,name='update'),
    path('<int:movie_pk>/delete/',views.delete,name='delete'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

08_pjt/movies/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=50)


class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    content = models.TextField()
    

movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta :
        model = Movie
        fields = '__all__'

08_pjt/movies/views.py
from django.shortcuts import render
from django.views.decorators.http import require_safe
from .models import Genre, Movie
from django.shortcuts import get_object_or_404, get_list_or_404


# Create your views here.
@require_safe
def index(request):
    movies = get_list_or_404(Movie)

    context = {
        "movies":movies,
    }

    return render(request, 'movies/index.html', context)
    


@require_safe
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)

    context = {
        "movie":movie,
    }

    return render(request, 'movies/detail.html', context)
    


@require_safe
def recommended(request):
    pass

movies/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm

def index(request):
    movies = Movie.objects.all()
    context = {
        'movies':movies,
    }
    return render(request, 'movies/index.html',context)

def create(request):
    if request.method =="POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:index")
    else:
        form = MovieForm()
    context = {
        'form':form,
    }
    return render(request,'movies/create.html',context)



def detail(request,movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    context = {
        'movie':movie,
    }
    return render(request,'movies/detail.html',context)
    

def update(request,movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == "POST":
        form = MovieForm(request.POST,instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail',movie_pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'movie':movie,
        'form':form,
    }
    return render(request,'movies/update.html',context)


def delete(request,movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.delete()
    return redirect("movies:index")

movies/templates/movies/create.html
{% extends "base.html" %}

{% block content %}
 <form action="{% url "movies:create" %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="글 제출">
 </form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
<h1>Detail</h1>
<h3>{{movie.pk}}번 영화</h3>
<h4>영화 제목: {{movie.title}}</h4>
<h4>영화 내용: {{movie.description}}</h4>
<hr>
<form action="{% url "movies:delete" movie.pk%}" method="POST">
    {% csrf_token %}
    <input type="submit" value="영화 삭제">
</form>



{% endblock content %}

movies/templates/movies/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<img src="{% static "movies/index.jpg" %}" alt="index_img">
<h1>INDEX PAGE</h1>
<a href="{% url "movies:create" %}">create</a>
<div class="container" >
    <div class = "row g-5">
    {% for movie in movies %}
        <div class="col-6 ">
            <div class = 'card'>
                <div class="card-body">
                    <a href="{% url "movies:detail" movie.pk %}"><h5 class="card-title">{{movie.title}}</h5></a>
                    {% comment %} <p class="card-text">{{movie.description}}</p> {% endcomment %}
                    <p>{{movie.created_at}}</p>
                    <p>좋아요 {{movie.like_users.all|length}}</p>
                    <form action="{% url "movies:likes" movie.pk %}" method="POST">
                        {% csrf_token %}
                        {% if request.user in movie.like_users.all %}
                        <input type="submit" value="좋아요 취소">
                        {% else %}
                        <input type="submit" value="좋아요">
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

movies/templates/movies/update.html
{% extends "base.html" %}

{% block content %}
<form action="{% url "movies:update" movie.pk %}" method= "POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="영화정보 업데이트">
</form>



{% endblock content %}