08_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

08_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_pk>/change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),

]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

08_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
# Create your models here.

class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name = 'followers' )

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    content = models.TextField()
    

08_pjt/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

08_pjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm
from django.http import JsonResponse


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('community:index')


@login_required
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
@require_POST
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user

    if me != you:
        if me in you.followers.all():
            you.followers.remove(me)
            is_followed = False
        else:
            you.followers.add(me)
            is_followed = True
        context = {
            'is_followed' : is_followed,
            'followings_count': you.followings.count(),
            'followers_count' : you.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', you.username)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserCreationForm
# Create your views here.


@require_http_methods(['POST','GET'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    
    # POST
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')

    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
@require_http_methods(['POST',])
def logout(request):
        auth_logout(request)
        return redirect('movies:index')


@require_http_methods(['POST','GET'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    
    # POST
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')

    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET','POST',])
def update(request):
    if request.method=='POST':
        form = CustomUserCreationForm(request.POST,instance = request.user)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm(instance=request.user)
    context = {
        'form':form,
    }
    return render(request,'accounts/update.html',context)


@require_http_methods(['POST',])
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("movies:index")


@require_http_methods(['GET','POST',])
def change_password(request, user_pk):
    if request.method=='POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request,'accounts/change_password.html',context)


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person' : person,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.follwers.add(request.user)
    return redirect('accounts:profile', person.username)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}


{% block content %}

<form action="{% url "accounts:change_password" user.pk%}" method = "POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="확인">
</form>

{% endblock content %}

accounts/templates/accounts/follow.html
{% extends "base.html" %}


{% block content %}

<h1>{{ person.username}} 님의 프로필</h1>

<hr>

<h2>{{ person.username }} 가 작성한 게시글</h2>
{% for movie in person.movie_set.all %}
<div>{{ movie.title }}</div>
{% endfor %}

<hr>

<h2>{{ person.username }} 가 작성한 댓글</h2>
{% for comment in person.comment_set.all %}
<div>{{ comment.content }}</div>
{% endfor %}

<hr>

<h2>{{ person.username }} 가 좋아요한 게시글</h2>
{% for movie in person.like_movies.all %}
<div>{{ movie.title }}</div>
{% endfor %}

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}


<form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="로그인">

</form>



{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}


{% block content %}

<h1>{{ person.username}} 님의 프로필</h1>

<div>
    <div>
        팔로잉 : {{ person.followings.all|length }} / 팔로워 : {{ person.followers.all|length }}
    </div>
    {% if request.user != person %}
    <div>
        <form action="{% url "accounts:follow" %}" method="POST">
            {% csrf_token %}
            {% if request.user in person.followers.all %}
            <input type="submit" value="Unfollow">
            {% else %}
            <input type="submit" value="Follow">
            {% endif %}
        </form>
    </div>
    {% endif %}
</div>






<hr>

<h2>{{ person.username }} 가 작성한 게시글</h2>
{% for movie in person.movie_set.all %}
<div>{{ movie.title }}</div>
{% endfor %}

<hr>

<h2>{{ person.username }} 가 작성한 댓글</h2>
{% for comment in person.comment_set.all %}
<div>{{ comment.content }}</div>
{% endfor %}

<hr>

<h2>{{ person.username }} 가 좋아요한 게시글</h2>
{% for movie in person.like_movies.all %}
<div>{{ movie.title }}</div>
{% endfor %}

{% if request.user == person %}

<form action="{% url "accounts:update"%}" method="POST">
    {% csrf_token %}
    <input type="submit" value="회원정보 변경">
</form>
{% endif %}


{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}

<form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="회원가입">

</form>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}
{% block content %}

<form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정">
</form>

<form action="{% url "accounts:delete" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="회원탈퇴">
  </form>

  <form action="{% url "accounts:change_password" user.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="비밀번호 변경 링크">
  </form>

{% endblock content %}