08_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_pk>/change_password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/',views.create,name='create'),
    path('<int:movie_pk>/',views.detail,name='detail'),
    path('<int:movie_pk>/update/',views.update,name='update'),
    path('<int:movie_pk>/delete/',views.delete,name='delete'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .logout_submit {
            background: none;
            border: none;
            font-size: 20px;
            padding: 0;
        }
    </style>
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    <nav class="navbar sticky-top bg-body-tertiary">
        <div class="container-fluid">
            <a href="{% url "movies:index" %}">MOVIEW</a>
            <div class="d-flex">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url "accounts:profile" user.username %}">내 프로필 보기</a>
                    <form class="d-flex" action="{% url "accounts:logout" %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" class="logout_submit" value="로그아웃">
                    </form>
                {% else %}
                    <a class="navbar-brand" href="{% url "accounts:signup" %}">회원가입</a>
                    <a class="navbar-brand" href="{% url "accounts:login" %}">로그인</a>
                {% endif %}
              
            </div>
     
        </div>
      </nav>


   <div>
  
   </div>
    {% block content %}{% endblock content %}
</body>
</html>